### ISSUE TITLE
Diplomancer 6.0.3.43 - does not include PhanxConfig libraries

### ISSUE THREAD

**Issue by Agramon** [Talyrius/Diplomancer#2]
Got error inside wow. Because none of the mentioned libs in Diplomancer.toc are included
Libs\PhanxConfig-Button\PhanxConfig-Button.lua
Libs\PhanxConfig-Checkbox\PhanxConfig-Checkbox.lua
Libs\PhanxConfig-Dropdown\PhanxConfig-Dropdown.lua
Libs\PhanxConfig-Header\PhanxConfig-Header.lua
Libs\PhanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua

Error:
Diplomancer\Options.lua:15: Cannot find a library instance of "PhanxConfig-OptionsPanel".

**Comment by Phanx** [comment]
Looks like the Curse packager screwed up... I'll tell it to try again.

**Comment by Phanx** [comment]
Verified that the 6.0.3.44 package was made correctly and includes all the libraries.
