### ISSUE TITLE
Insane numbers with 'exalted' reputations...

### ISSUE THREAD

**Issue by ZaephirMoth** [Talyrius/Diplomancer#8]
Greetings !

  I thank you a lot for this great addon, which works well indeed, but wanted to report a (very) minor glitch, which may or may not be Diplomancer's fault... 
  
  I'm currently using an interface based on Dominos, including an 'all-in-one' bar which serves to display experience, reputations, artefact power, etc. This one will always show the numbers related to any reputation level and faction, **even when it reached its maximum score** (of 999/999 past 'exalted' status), and that's the reason of this glitch, otherwise unnoticeable with Blizzard's default UI. 
  Because any 'exalted' reputation watched, at least 'vanilla' ones - since I've only been playing 'vanilla' characters lately -, will display absurd numbers instead of '21000 / 21000' (or '0 / 999' for the remaining points above 'exalted'). You'll get instead, for example, '-2147483648 / 0'. This doesn't concern a specific reputation, zone, subzone, faction tabard, other addon - I disabled everything to test it - or whatever, but rather seems a general issue.
  As I said, it's quite a minor glitch and I can perfectly well live with it ^^, but it seemed worth reporting anyway.

  Cheers !
  Benjamin

**Comment by Talyrius** [comment]
Diplomancer just changes which faction is being watched. It doesn't have any control over how that faction is presented to you. It sounds like the all-in-one bar addon you're using hasn't been updated to properly represent Paragon reputation (added in patch 7.2) on the reputation bar.

**Comment by ZaephirMoth** [comment]
Thanks for the answer. I was speaking about 'vanilla' WoW, so I didn't thought about the paragon system, which doesn't concern those reputations... But you're right : it certainly comes from the other addon... I'll post the same remark overthere.
