### ISSUE TITLE
Diplomancer error

### ISSUE THREAD

**Issue by als30334** [Talyrius/Diplomancer#9]
6x Diplomancer\Core.lua:115: attempt to call global 'GetCurrentMapAreaID' (a nil value)
Diplomancer\Core.lua:115: in function `GetCurrentMapAreaID'
Diplomancer\Core.lua:130: in function `Update'
Diplomancer\Core.lua:239: in function `?'
Diplomancer\Core.lua:45: in function <Diplomancer\Core.lua:45>

Locals:
self = <table> {
 GetCurrentMapAreaID = <function> defined @Diplomancer\Core.lua:107
 PickBestFaction = <function> defined @Diplomancer\Core.lua:261
 ZONE_CHANGED = <function> defined @Diplomancer\Core.lua:218
 Update = <function> defined @Diplomancer\Core.lua:118
 racialFaction = 69
 localized = true
 LocalizeData = <function> defined @Diplomancer\Data.lua:12
 subzoneFactions = <table> {
 }
 zoneFactions = <table> {
 }
 L = <table> {
 }
 EventFrame = <unnamed> {
 }
 OptionsPanel = <unnamed> {
 }
 SetWatchedFactionByID = <function> defined @Diplomancer\Core.lua:282
 GetChampionedFaction = <function> defined @Diplomancer\Core.lua:313
 Debug = <function> defined @Diplomancer\Core.lua:21
 ZONE_CHANGED_NEW_AREA = <function> defined @Diplomancer\Core.lua:218
 championFactions = <table> {
 }
 RestoreFactionHeaders = <function> defined @Diplomancer\Core.lua:399
 UNIT_INVENTORY_CHANGED = <function> defined @Diplomancer\Core.lua:247
 ACTIONBAR_UPDATE_USABLE = <function> defined @Diplomancer\Core.lua:233
 LibBabble-SubZone-3.0-LoadingLib = <table> {
 }
 GetFactionIDFromName = <function> defined @Diplomancer\Core.lua:331
 championZones = <table> {
 }
 GetFactionNameFromID = <function> defined @Diplomancer\Core.lua:354
 PLAYER_ENTERING_WORLD = <function> defined @Diplomancer\Core.lua:218
 Print = <function> defined @Diplomancer\Core.lua:31
 ZONE_CHANGED_INDOORS = <function> defined @Diplomancer\Core.lua:218
 ExpandFactionHeaders = <function> defined @Diplomancer\Core.lua:379
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetCurrentMapAreaID' (a nil value)"

**Comment by Talyrius** [comment]
Fixed via a6da259.
